version: '3.7'
services:
  db:
    image: postgres:9.6
    env_file: .env
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

  djangofest:
    build: ./djangofest
    command: python manage.py runserver 0.0.0.0:8000
    env_file: .env
    volumes:
      - ./djangofest:/djangofest
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DJANGO_SETTINGS_MODULE=djangofest.settings.dev
      - PYTHONUNBUFFERED=1

  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"

  celery:
    build: ./djangofest
    command: watchmedo auto-restart --directory=/api/ --pattern=*.py --recursive -- celery worker -A  djangofest -B -l info -Q djangofest
    depends_on:
      - redis
    env_file: .env
    environment:
      - DJANGO_SETTINGS_MODULE=djangofest.settings.dev
      - TZ=America/Bogota
    volumes:
      - ./djangofest:/api
